### ISSUE TITLE
Program crashes when scale calibration cannot be written

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/BrillouinAcquisition#208]
If the currently selected directory is read-only (e.g. c:\program files) writing the scale calibration file fails and makes the program crash.

**Comment by kyoohkim** [comment]
![errorMSG](https://user-images.githubusercontent.com/65673531/134521879-086819d9-e088-465f-8a71-2f4f36558539.png)

The error is not resolved although the currently selected directory is writable.
I checked that the software can acquire and save brightfield images in the same folder.

**Comment by raimund-schluessler** [comment]
> 
> 
> ![errorMSG](https://user-images.githubusercontent.com/65673531/134521879-086819d9-e088-465f-8a71-2f4f36558539.png)
> 
> The error is not resolved although the currently selected directory is writable.
> I checked that the software can acquire and save brightfield images in the same folder.

Hm, your issue is unrelated to the writable directory. I'll create a separate issue.
